export const skills = [
  {
    name: 'HTML5',
    image: './img/icons/HTML5-logo.png',
    altText: 'HTML5 Logo',
    titleText: 'HTML5',
  },
  {
    name: 'CSS',
    image: './img/icons/CSS-logo.png',
    altText: 'CSS Logo',
    titleText: 'CSS',
  },
  {
    name: 'JavaScript',
    image: './img/icons/JS-logo.png',
    altText: 'JavaScript Logo',
    titleText: 'JavaScript',
  },
  {
    name: 'React Native',
    image: './img/icons/React-Native-Logo.png',
    altText: 'React Native Logo',
    titleText: 'React Native',
  },
  {
    name: 'PostgreSQL',
    image: './img/icons/postgresql-icon.png',
    altText: 'PostgreSQL Logo',
    titleText: 'PostgreSQL',
  },
  {
    name: 'Express JS',
    image: './img/icons/Express_Logo.png',
    altText: 'Express JS Logo',
    titleText: 'Express JS',
  },
  {
    name: 'React',
    image: './img/icons/React-logo.png',
    altText: 'React Logo',
    titleText: 'React',
  },
  {
    name: 'Node JS',
    image: './img/icons/Node-Js-Logo.png',
    altText: 'Node JS Logo',
    titleText: 'Node JS',
  },
  {
    name: 'Tailwind CSS',
    image: './img/icons/Tailwind-CSS-Logo.png',
    altText: 'Tailwind CSS Logo',
    titleText: 'Tailwind CSS',
  },
  {
    name: 'Git',
    image: './img/icons/Git-Logo.png',
    altText: 'Git Logo',
    titleText: 'Git',
  },
  {
    name: 'Responsive Design',
    image: './img/icons/Responsive-Design-Icon.png',
    altText: 'Responsive Design Image',
    titleText: 'Responsive Design',
  },
  {
    name: 'Testing',
    image: './img/icons/Testing-logo.png',
    altText: 'Testing Logo Image',
    titleText: 'Testing Logo',
  },
  // {
  //   name: 'Accessibility',
  //   image: './img/icons/Accessibility_logo.png',
  //   altText: 'Accessibility Logo Image',
  //   titleText: 'Accessibility Logo',
  // },
];
